### PR TITLE
Support bf16 weight and dynamic shape

### PR DESCRIPTION
**Pull request by yuanzhedong**
* Fix crash when weight is not support by numpy(e.g. BFloat16)
* Fix crash when the shape is dynamic(not an integer)

### CODE REVIEW

**Comment by yuanzhedong** [comment]
image

**Comment by yuanzhedong** [comment]
Hi @jinjingforever, could you take a look when have time? Thank you!

**Comment by jinjingforever** [comment]
Thanks @yuanzhedong! I will let @yijie-yang take a look.

**Review by yijie-yang — APPROVED** [review]
Thank you, lgtm!

**Comment by yuanzhedong** [comment]
> Thank you, lgtm!

Thank you! Just fixed the format using
```
pyink --pyink-use-majority-quotes --pyink-indentation=2 --preview --unstable --line-length 80 --extend-exclude .downloads --extend-exclude "\.pyi" ./
```

**Pull request merged**
