### PR TITLE
Move tensor to cpu for json dump

### PR DESCRIPTION
**Pull request by yuanzhedong**

### CODE REVIEW

**Comment by yijie-yang** [comment]
Thank you Yuanzhe! Your PR should resolve this issue: https://github.com/google-ai-edge/model-explorer/issues/57. Shall we link it to your PR?

**Review by yijie-yang — APPROVED** [review]
Thank you!

**Comment by yuanzhedong** [comment]
> Thank you Yuanzhe! Your PR should resolve this issue: #57. Shall we link it to your PR?

Thank you Yijie, feel free to link it!

A follow up question, do you know when this change will be available to download through the prebuilt wheel?
```
pip install ai-edge-model-explorer \
    --index-url https://download.pytorch.org/whl/cpu \
    --extra-index-url https://pypi.python.org/simple
```

**Comment by yijie-yang** [comment]
> > Thank you Yuanzhe! Your PR should resolve this issue: #57. Shall we link it to your PR?
> 
> Thank you Yijie, feel free to link it!
> 
> A follow up question, do you know when this change will be available to download through the prebuilt wheel?
> 
> ```
> pip install ai-edge-model-explorer \
>     --index-url https://download.pytorch.org/whl/cpu \
>     --extra-index-url https://pypi.python.org/simple
> ```



> > Thank you Yuanzhe! Your PR should resolve this issue: #57. Shall we link it to your PR?
> 
> Thank you Yijie, feel free to link it!
> 
> A follow up question, do you know when this change will be available to download through the prebuilt wheel?
> 
> ```
> pip install ai-edge-model-explorer \
>     --index-url https://download.pytorch.org/whl/cpu \
>     --extra-index-url https://pypi.python.org/simple
> ```

Let's merge the PR now. The new build will be available this afternoon.

**Pull request merged**
